apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:582d3785b179b8708e106c46953df5484da54e8fa8c8795ea1284025346b55c3
  name: app-image
  newName: docker.io/georgevazj/gitops-demo
namespace: argocd
