apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml

labels:
- pairs:
    kind: microservice
    lang: nodejs
    project: gitops-demo
    region: westeurope

commonAnnotations:
  description: GitOps demo
  source: kustomize
  team: sanacloud

images:
- digest: sha256:f094a61418e6558a2abe4abaca805da8e2e3f29002a27a8101878857982ee77f
  name: app-image
  newName: docker.io/georgevazj/gitops-demo
namespace: argocd

replicas:
- count: 1
  name: gitops-demo
nameSuffix: -playground
