apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml

labels:
  - pairs:
      project: gitops-demo
      region: westeurope
      kind: microservice
      lang: nodejs

commonAnnotations:
  team: sanacloud
  description: "GitOps demo"
  source: kustomize

images:
- digest: sha256:69e23dac6765aa6ace146092b424698052ff68113c5e87fe954cb6df1dc4497b
  name: app-image
  newName: docker.io/georgevazj/gitops-demo
namespace: argocd

replicas:
- name: gitops-demo
  count: 3

nameSuffix: -playground