apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
images:
  - name: "app-image"
    newName: docker.io/georgevazj/gitops-demo
    newTag: latest
namespace: argocd