apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- name: app-image
  newName: docker.io/georgevazj/gitops-demo:sha256
  newTag: 8df6e3686d1d506322d250f9c99405ba8081d3978615afcb045f6f6ae53ce65a
namespace: argocd
