apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml

labels:
- pairs:
    kind: microservice
    lang: nodejs
    project: gitops-demo
    region: westeurope

commonAnnotations:
  description: GitOps demo
  source: kustomize
  team: sanacloud

images:
- digest: sha256:ac5d5bdfe1bfc5da0ace3cfac28359ac580863facbab54e0a225335c51585d2f
  name: app-image
  newName: docker.io/georgevazj/gitops-demo
namespace: argocd

replicas:
- count: 1
  name: gitops-demo
nameSuffix: -playground
