apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml

labels:
- pairs:
    kind: microservice
    lang: nodejs
    project: gitops-demo
    region: westeurope

commonAnnotations:
  description: GitOps demo
  source: kustomize
  team: sanacloud

images:
- digest: sha256:d8328102d6983eff52d0e909943011f6f257dd25115bf135361636e3db0abbe1
  name: app-image
  newName: docker.io/georgevazj/gitops-demo
namespace: argocd

replicas:
- count: 3
  name: gitops-demo
nameSuffix: -playground
