apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:24f97c995020448d9901d3151ee13bc052bd091d48365a643a03a072872a4a49
  name: app-image
  newName: docker.io/georgevazj/gitops-demo
namespace: argocd
