apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- name: app-image
  newName: gitops-demo:sha256
  newTag: 4460e3bd893e4461bdf0d6dbbbc6a216f3b09664df59726ef15ec715293db801
namespace: argocd
