apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- name: app-image
  newName: docker.io/georgevazj/georgevazj:sha256
  newTag: ed4d7ec131bb2bd19f2a4e4902e1cf57718fdba194aedda7116b589f72e80862
namespace: argocd
