apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml

labels:
- pairs:
    kind: microservice
    lang: nodejs
    project: gitops-demo
    region: westeurope

commonAnnotations:
  description: GitOps demo
  source: kustomize
  team: sanacloud

images:
- digest: sha256:213271d1d251f0d452e9923ec63c405d2ce6eaaf7c085eb284d06d4532c303c6
  name: app-image
  newName: docker.io/georgevazj/gitops-demo
namespace: argocd

replicas:
- count: 1
  name: gitops-demo
nameSuffix: -playground
