apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml

labels:
- pairs:
    kind: microservice
    lang: nodejs
    project: gitops-demo
    region: westeurope

commonAnnotations:
  description: GitOps demo
  source: kustomize
  team: sanacloud

images:
- digest: sha256:07f110ea983d078821878a50950e42402bd333903bc92063cc022c0ef9c9065e
  name: app-image
  newName: docker.io/georgevazj/gitops-demo
namespace: argocd

replicas:
- count: 1
  name: gitops-demo
nameSuffix: -playground
