apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:59bbc6bd7fd4fe1310a501eb94844fd49ce32bf7f68dbb126edde2f72b05f31a
  name: app-image
  newName: docker.io/georgevazj/gitops-demo
namespace: argocd
