apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gitops-demo-playground
    app.kubernetes.io/instance: gitops-demo-playground
  name: gitops-demo
  namespace: argocd
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: gitops-demo-playground
    weight: 100
  wildcardPolicy: None
