name: Gitops
env:
  APP_NAME: "gitops-demo"
  IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}
  IMAGE_REGISTRY_USER: ${{ secrets.IMAGE_REGISTRY_USER }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
  IMAGE_TAGS: ""

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    environment: playground
    outputs:
      image: ${{ steps.build-image.outputs.image }}
      digest: ${{ steps.push-image.outputs.digest }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Determine app name
      if: env.APP_NAME == ''
      run: |
        echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
    
    - name: Determine image tags
      if: env.IMAGE_TAGS == ''
      run: |
        echo "IMAGE_TAGS=${GITHUB_SHA}" | tee -a $GITHUB_ENV

    # https://github.com/redhat-actions/buildah-build#readme
    - name: Build from Dockerfile
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}
        tags: ${{ env.IMAGE_TAGS }}

        # If you don't have a Dockerfile/Containerfile, refer to https://github.com/redhat-actions/buildah-build#scratch-build-inputs
        # Or, perform a source-to-image build using https://github.com/redhat-actions/s2i-build
        # Otherwise, point this to your Dockerfile/Containerfile relative to the repository root.
        dockerfiles: |
          ./Dockerfile

    # Docker login is required to push to the image registry.
    - name: Docker login
      run: |
        docker login -u ${{ secrets.IMAGE_REGISTRY_USER }} -p ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
    
    # https://github.com/redhat-actions/push-to-registry#readme
    - name: Push to registry
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.IMAGE_REGISTRY_USER }}
        password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
        tls-verify: true

  update-manifests:
    name: Update manifests
    needs: "build-and-push"
    runs-on: ubuntu-latest
    environment: playground
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update manifests with kustomize
      working-directory: "base"
      run: |
          kustomize edit set image app-image=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REGISTRY_USER }}:${{ needs.build-and-push.outputs.digest }}
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Update deployment image tag to ${{ needs.build-and-push.outputs.digest }}